
services:
  ais-frontend:
    image: registry.zepto.vn/ais/ais-portal-nextjs:latest
    container_name: ais-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # If the container goes down, it will restart
    restart: "always"
    networks:
      - base-project

networks:
  base-project:
    external: true